- name: install nginx
  apt: pkg=nginx state=present
# TODO firewall idempotency
# - name: allow HTTP connections
#   command: ufw allow http

- name: Remove link to default site
  notify: reload nginx
  file: dest=/etc/nginx/sites-enabled/default
        state=absent
- name: "Dummy site for stray web requests, nginx status page"
  notify: reload nginx
  copy: src=etc/nginx/sites-enabled/dummy
        dest=/etc/nginx/sites-enabled/dummy
        mode=0644
- name: Basic security settings
  notify: reload nginx
  copy: src=etc/nginx/conf.d/security.conf
        dest=/etc/nginx/conf.d/security.conf
        mode=0644

- name: start nginx
  service: name=nginx state=started enabled=true
