---

- hosts: all
  accelerate: true
  user: "{{admin_name}}"
  sudo: true
  vars_files:
  - vars/secrets.yml

  roles:
    # TODO idempotency
    # - firewall # make idempotent.
    # - bootstrap # make fw rule for accelerate idempotent

    - common
    - datadog
    - mysql
    - nginx
    - fpm
    - wordpress

    - wordpress-custom
