---
- name: install php-fpm and deps
  apt: pkg=$item state=present
  with_items:
    - libapache2-mod-auth-mysql
    - php5-mysql
    - php5-fpm

# - name: Disable default pool
#   command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
#   notify: restart php-fpm

- name: configure fpm fix_pathinfo
  lineinfile: dest=/etc/php5/fpm/php.ini regexp=^cgi\.fix_pathinfo
              line=cgi.fix_pathinfo=0
- name: configure fpm to not advertise the version
  lineinfile: dest=/etc/php5/fpm/php.ini regexp=^expose_php
              line='expose_php = Off'
  notify: restart fpm

- name:
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp=^listen
              line='listen = /var/run/php5-fpm.sock'
  notify: restart fpm

- name: Logrotate the fpm log
  template: src=etc/logrotate.d/fpm.j2 dest=/etc/logrotate.d/fpm
