---
- name: Download the Wordpress Jetpack plugin
  get_url:  url=http://downloads.wordpress.org/plugin/jetpack.{{ jetpack_version }}.zip
            dest=/srv/jetpack.{{ jetpack_version }}.zip
            # Changes every request, for some reason. Can't check the SHA :-(
            # sha256sum=
  notify:
    - uninstall jetpack
    - install jetpack
  tags: jetpack
