- name: Install ufw
  apt: pkg=ufw state=present
- name: deny connections by default
  command: ufw default deny
  changed_when: false # FIXME
- name: allow SSH connections
  command: ufw allow ssh
  changed_when: false # FIXME
- name: enable ufw
  command: ufw --force enable
  changed_when: false # FIXME
